# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b28139e030969a20d83b96c0202c7cf"
name = "Gw Tier Discount"
application_url = "https://example.com"
embedded = true
handle = "gw-bulk-tier-discount"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_discounts,read_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
